import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      {/* <body className="min-h-full flex flex-col">{children}</body> */}
      <body>
      <div className="flex h-screen">
      {/* Sidebar - 20% */}
      <div className="w-[15%]">
        <Sidebar />
      </div>

      {/* Main Content - 80% */}
      <div className="w-[85%] p-6 bg-gray-50 overflow-y-auto">
        {children}
      </div>
      </div>
      </body>
    </html>
  );
}
